/*
    Copyright 2008 Wolfgang Ginolas

    This file is part of P2PVPN.

    P2PVPN is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.p2pvpn.gui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.p2pvpn.network.Router;
import org.p2pvpn.network.RoutungTableListener;

public class MainWindow extends javax.swing.JFrame implements RoutungTableListener {

	private MainControl mainControl;
	private NewNetwork newNetwork;
	private OptionWindow optionWindow;
	private InviteWindow inviteWindow;
	private AcceptWindow acceptWindow;

	private PeerListModel peerListModel;
	private PeerListCellRenderer peerListCellRenderer;
	
    /** Creates new form MainWindow */
    public MainWindow() {
		peerListModel = new PeerListModel();
		peerListCellRenderer = new PeerListCellRenderer();
        initComponents();
		try {
			URL url = InfoWindow.class.getClassLoader().getResource("resources/images/P2PVPN-32.png");
			setIconImage(new ImageIcon(url).getImage());
		} catch(NullPointerException e) {}
		
		setButtonIcon(btnNewNet, "resources/images/new.png");
		setButtonIcon(btnInvite, "resources/images/invite.png");
		setButtonIcon(btnAccept, "resources/images/accept.png");
		setButtonIcon(btnOptions, "resources/images/options.png");
		setButtonIcon(btnInfo, "resources/images/info.png");
		
		mainControl = new MainControl(this);
		newNetwork = new NewNetwork(this, mainControl);
		optionWindow = new OptionWindow(this);
		inviteWindow = new InviteWindow(this, mainControl);
		acceptWindow = new AcceptWindow(this, mainControl);
		
		mainControl.start();
    }

	private void setButtonIcon(JButton btn, String path) {
		try {
			btn.setIcon(new ImageIcon(InfoWindow.class.getClassLoader().getResource(path)));
			btn.setText("");
		} catch (NullPointerException e) {
			System.err.println("could not load "+path);
		}
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNewNet = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnInvite = new javax.swing.JButton();
        btnOptions = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPeers = new javax.swing.JList();
        btnInfo = new javax.swing.JButton();
        txtNetwork = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P2PVPN");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnNewNet.setText("N");
        btnNewNet.setToolTipText("New Network...");
        btnNewNet.setFocusable(false);
        btnNewNet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewNet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewNet);

        btnAccept.setText("A");
        btnAccept.setToolTipText("Accept Invitation...");
        btnAccept.setFocusable(false);
        btnAccept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccept.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccept);

        btnInvite.setText("I");
        btnInvite.setToolTipText("Invite someone...");
        btnInvite.setFocusable(false);
        btnInvite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInvite.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInvite);

        btnOptions.setText("O");
        btnOptions.setToolTipText("Options...");
        btnOptions.setFocusable(false);
        btnOptions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOptions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOptions);

        btnChat.setText("C");
        btnChat.setFocusable(false);
        btnChat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnChat);
        jToolBar1.add(jSeparator1);

        lblName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblName.setText("Name");
        jToolBar1.add(lblName);

        lstPeers.setModel(peerListModel);
        lstPeers.setCellRenderer(peerListCellRenderer);
        jScrollPane1.setViewportView(lstPeers);

        btnInfo.setText("I");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        txtNetwork.setText("Network");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtNetwork)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(btnInfo))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInfo)
                    .addComponent(txtNetwork)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnNewNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNetActionPerformed
// TODO add your handling code here:
	newNetwork.setVisible(true);
}//GEN-LAST:event_btnNewNetActionPerformed

private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
// TODO add your handling code here:
	InfoWindow.open(mainControl.getConnectionManager());
}//GEN-LAST:event_btnInfoActionPerformed

private void btnOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionsActionPerformed
// TODO add your handling code here:
	optionWindow.setNodeName(mainControl.getName());
	optionWindow.setPort(mainControl.getServerPort());
	optionWindow.setIP(mainControl.getIp());
	optionWindow.setVisible(true);
	if (optionWindow.isOk()) {
		mainControl.setName(optionWindow.getNodeName());
		mainControl.setServerPort(optionWindow.getPort());
		mainControl.setIp(optionWindow.getIP());
	}
}//GEN-LAST:event_btnOptionsActionPerformed

private void btnInviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviteActionPerformed
// TODO add your handling code here:
	inviteWindow.setVisible(true);
}//GEN-LAST:event_btnInviteActionPerformed

private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
// TODO add your handling code here:
	acceptWindow.setVisible(true);
}//GEN-LAST:event_btnAcceptActionPerformed


	public void setNodeName(String name) {
		lblName.setText(name);
	}
	
	public void networkHasChanged() {
		btnInvite.setEnabled(mainControl.getNetworkCfg()!=null);
		peerListModel.setConnectionManager(mainControl.getConnectionManager());
		peerListCellRenderer.setMainControl(mainControl);
		if (mainControl.getConnectionManager()!=null) {
			mainControl.getConnectionManager().getRouter().addTableListener(this);
			lblName.setToolTipText(null);
			tableChanged(mainControl.getConnectionManager().getRouter());
		}
		if (mainControl.getAccessCfg()==null) {
			txtNetwork.setText("not connected");
		} else {
			txtNetwork.setText(mainControl.getAccessCfg().getProperty("network.name", ""));
		}
	}
	
	public void tableChanged(Router router) {
		lblName.setToolTipText(mainControl.descriptionForPeer(mainControl.getConnectionManager().getLocalAddr()));
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnInvite;
    private javax.swing.JButton btnNewNet;
    private javax.swing.JButton btnOptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblName;
    private javax.swing.JList lstPeers;
    private javax.swing.JLabel txtNetwork;
    // End of variables declaration//GEN-END:variables

}
